version: '3.8'

services:
  web:
    stdin_open: true
    tty: true
    container_name: dentistry_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
