describe('Patients', () => {
  it('Table of patients is displayed', () => {
    cy.visit('http://localhost:3000/login')
    cy.get('#login_username').as('username')
    cy.get('#login_password').as('password')
    cy.get('button[type="submit"]').as('loginButton')
    cy.get('@username').type('m')
    cy.get('@password').type('pi3.1415')
    cy.get('@loginButton').click()
    cy.get('.ant-layout-sider-children > .ant-menu > :nth-child(3)').as('patientsSidebar')
    cy.get('@patientsSidebar').click()
    cy.contains('New Patient')
    cy.contains('Name')
    cy.contains('Last Name')
    cy.contains('ID')
    cy.contains('Phone')
    cy.contains('Age')
    cy.contains('Actions')
  })
})
