describe('Patients', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/login')
    cy.get('#login_username').as('username')
    cy.get('#login_password').as('password')
    cy.get('button[type="submit"]').as('loginButton')
    cy.get('@username').type('m')
    cy.get('@password').type('pi3.1415')
    cy.get('@loginButton').click()
    cy.get('.ant-layout-sider-children > .ant-menu > :nth-child(3)').as('patientsSidebar')
    cy.get('@patientsSidebar').click()
  })

  it('Table of patients is displayed', () => {
    cy.contains('New Patient')
    cy.contains('Name')
    cy.contains('Last Name')
    cy.contains('ID')
    cy.contains('Phone')
    cy.contains('Age')
    cy.contains('Actions')
  })

  it('Patient is created with basic information', () => {
    cy.get('.ant-btn').as('createNewPatient')
    cy.get('@createNewPatient').click()
    cy.get('#personalInformation_firstName').as('firstName')
    cy.get('@firstName').type('John')
    cy.get('#personalInformation_lastName').as('lastName')
    cy.get('@lastName').type('Smith')
    cy.get('#personalInformation_idDocumentNumber').as('idDocumentNumber')
    cy.get('@idDocumentNumber').type('0987654321')
    cy.get('#personalInformation_sex').as('sex')
    cy.get('@sex').click()
    cy.contains('Male').click()
    cy.get('#personalInformation_maritalStatus').click()
    cy.contains('Single').click()
    cy.get('#personalInformation_birthdate').as('birthdate')
    cy.get('@birthdate').click()
    cy.get('@birthdate').type('1990-01-01')
    cy.get('#personalInformation_referralSource').click()
    cy.contains('Other').click()
    cy.get('.ant-btn').click()
    cy.get('#contactInformation_phone').as('phone')
    cy.get('@phone').type('+593987654321')
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 500)
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 0)
    cy.contains('John')
    cy.contains('Smith')
  })

  it('Patient is deleted', () => {
    cy.get('svg.svg-inline--fa.fa-trash-alt.fa-w-14').first().click()
    cy.get('.ant-btn-dangerous').click()
    cy.contains('0987654321').should('not.exist')
    cy.contains('+593987654321').should('not.exist')
  })

  it('Patient is created with full information', () => {
    cy.get('.ant-btn').as('createNewPatient')
    cy.get('@createNewPatient').click()
    cy.get('#personalInformation_firstName').as('firstName')
    cy.get('@firstName').type('Peter')
    cy.get('#personalInformation_middleName').as('middleName')
    cy.get('@middleName').type('James')
    cy.get('#personalInformation_lastName').as('lastName')
    cy.get('@lastName').type('Johnson')
    cy.get('#personalInformation_secondLastName').as('secondLastName')
    cy.get('@secondLastName').type('Hidalgo')
    cy.get('#personalInformation_idDocumentNumber').as('idDocumentNumber')
    cy.get('@idDocumentNumber').type('0123456789')
    cy.get('#personalInformation_sex').as('sex')
    cy.get('@sex').click()
    cy.contains('Male').click()
    cy.get('#personalInformation_maritalStatus').click()
    cy.contains('Single').click()
    cy.get('#personalInformation_jobTitle').as('jobTitle')
    cy.get('@jobTitle').type('Aerospace Engineer')
    cy.get('#personalInformation_birthdate').as('birthdate')
    cy.get('@birthdate').click()
    cy.get('@birthdate').type('1990-01-01')
    cy.get('#personalInformation_referralSource').click()
    cy.contains('Other').click()
    cy.get('.ant-btn').click()

    cy.get('#contactInformation_addressLine').as('addressLine')
    cy.get('@addressLine').type('Sierra Bonita 123')
    cy.get('#contactInformation_phone').as('phone')
    cy.get('@phone').type('+593987654312')
    cy.get('#contactInformation_whatsapp').as('whatsapp')
    cy.get('@whatsapp').click()
    cy.get('#contactInformation_email').as('email')
    cy.get('@email').type('peter.johnson@gmail.com')
    cy.get('#contactInformation_healthInsuranceCompany').as('healthInsuranceCompany')
    cy.get('@healthInsuranceCompany').type('Salud S.A.')

    cy.get('#contactInformation_emergencyContactName').as('emergencyContactName')
    cy.get('@emergencyContactName').type('Albert Einstein')
    cy.get('#contactInformation_emergencyContactPhone').as('emergencyContactPhone')
    cy.get('@emergencyContactPhone').type('+13053991321')

    cy.get('#contactInformation_representative').as('representative')
    cy.get('@representative').click()
    cy.get('#contactInformation_representativeName').as('representativeName')
    cy.get('@representativeName').type('Isaac Newton')
    cy.get('#contactInformation_representativePhone').as('emergencyContactPhone')
    cy.get('@emergencyContactPhone').type('+13053991321')
    cy.get('#contactInformation_representativeRelationship').as('representativeRelationship')
    cy.get('@representativeRelationship').type('Best friend')

    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 500)
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 0)
    cy.contains('Peter')
    cy.contains('Johnson')

    cy.get('svg.svg-inline--fa.fa-trash-alt.fa-w-14').first().click()
    cy.get('.ant-btn-dangerous').click()
    cy.contains('0123456789').should('not.exist')
    cy.contains('+593987654312').should('not.exist')
  })

  it('Patient is edited', () => {
    cy.get('.ant-btn').as('createNewPatient')
    cy.get('@createNewPatient').click()
    cy.get('#personalInformation_firstName').as('firstName')
    cy.get('@firstName').type('ThisIsMyName')
    cy.get('#personalInformation_lastName').as('lastName')
    cy.get('@lastName').type('Black')
    cy.get('#personalInformation_idDocumentNumber').as('idDocumentNumber')
    cy.get('@idDocumentNumber').type('0987654321')
    cy.get('#personalInformation_sex').as('sex')
    cy.get('@sex').click()
    cy.contains('Male').click()
    cy.get('#personalInformation_maritalStatus').click()
    cy.contains('Single').click()
    cy.get('#personalInformation_birthdate').as('birthdate')
    cy.get('@birthdate').click()
    cy.get('@birthdate').type('1990-01-01')
    cy.get('#personalInformation_referralSource').click()
    cy.contains('Other').click()
    cy.get('.ant-btn').click()
    cy.get('#contactInformation_phone').as('phone')
    cy.get('@phone').type('+593987654321')
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 500)
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 0)
    cy.contains('ThisIsMyName')
    cy.contains('Black')

    cy.get('svg.svg-inline--fa.fa-edit.fa-w-18').first().click()
    cy.get('@firstName').clear()
    cy.get('@firstName').type('ThisIsEditedName')
    cy.get('.ant-btn').click()
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 500)
    cy.get('.ant-row > .ant-btn').click()
    cy.scrollTo(0, 0)
    cy.contains('ThisIsMyName').should('not.exist')
    cy.contains('ThisIsEditedName')
    cy.contains('Black')

    cy.get('svg.svg-inline--fa.fa-trash-alt.fa-w-14').first().click()
    cy.get('.ant-btn-dangerous').click()
  })
})
